AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/factories.rb'
    - 'db/migrate/*.rb'
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'frontend/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.4

Rails:
  Enabled: true

Naming/AccessorMethodName:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: 'lf'

Naming/FileName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Style/MultilineBlockChain:
  Enabled: false

Style/OneLineConditional:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/WhileUntilModifier:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# TODO Temporarily disabled, because there is no time for correction
Rails/HasManyOrHasOneDependent:
  Enabled: false

# TODO Temporarily disabled, because there is no time for correction
Rails/InverseOf:
  Enabled: false
